// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiwbFtTnhFZsgFpX8AyMPniKYXiIZWHSs',
    appId: '1:555506100041:web:e9d4de11701cd7acd4dc98',
    messagingSenderId: '555506100041',
    projectId: 'warehouse-d91f8',
    authDomain: 'warehouse-d91f8.firebaseapp.com',
    storageBucket: 'warehouse-d91f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlC6yrn8vQvWMIQPAp9JeDXbwgBah_0SY',
    appId: '1:555506100041:android:1ea5788abc234dfbd4dc98',
    messagingSenderId: '555506100041',
    projectId: 'warehouse-d91f8',
    storageBucket: 'warehouse-d91f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByr0W0xjuQdSnpEjnSyLE7fYcK0lQqm0Y',
    appId: '1:555506100041:ios:6e8f53ab6c90f42ad4dc98',
    messagingSenderId: '555506100041',
    projectId: 'warehouse-d91f8',
    storageBucket: 'warehouse-d91f8.appspot.com',
    iosBundleId: 'com.example.irgisad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByr0W0xjuQdSnpEjnSyLE7fYcK0lQqm0Y',
    appId: '1:555506100041:ios:b3226075c0a71d46d4dc98',
    messagingSenderId: '555506100041',
    projectId: 'warehouse-d91f8',
    storageBucket: 'warehouse-d91f8.appspot.com',
    iosBundleId: 'com.example.irgisad.RunnerTests',
  );
}
